linux-on-mac/mbpfan

src/mbpfan.c

The daemon refuses to start on the mainline kernel (currently 4.0.0-1) because of the kernel version number, however it runs correctly if the version check is altered.

Altered kernel version check to allow 4.x.x kernels

---

src/mbpfan.c

This should fix #72 
The +3 should be for 1 null byte and 2 integers.

Fix buffer overflow in sprintf

---

AUTHORS
README.md

Thanks for merging my previous PR. I thought rather than just leave the clang info in the PR notes, I'd update the README.md to provide the basic instructions on how to compile with Clang. I have also updated the author info to provide my email address. As new versions of mbpfan and clang are released I will continue to test and update. I also may begin work on updating the Makefile to make it easier to use both.

Clang related instruction

---

README.md

```
sudo dmidecode -s system-product-name
Macmini5,3
```
```
uname -a
Linux elementaty-mini 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
sudo make tests
make install
make[1]: Entering directory '/home/wmoore/Source/mbpfan'
make
make[2]: Entering directory '/home/wmoore/Source/mbpfan'
Linking...
g++  -g -lm  src/settings.o src/daemon.o src/mbpfan.o src/main.o src/minunit.o src/strmap.o -lm -o bin/mbpfan
make[2]: Leaving directory '/home/wmoore/Source/mbpfan'
install -d /usr/sbin
install -d /etc
install -d /lib/systemd/system
install -d /usr/share/doc/mbpfan
install bin/mbpfan /usr/sbin
install -m644 mbpfan.conf /etc
install -m644 README.md /usr/share/doc/mbpfan
install -d /usr/share/man/man8
install -m644 mbpfan.8.gz /usr/share/man/man8 …
```

Add Macmini5,3 to supported list

---

src/mbpfan.c

On ubuntu 16.10 with the provided mbpfan.service file, mbpfan runs with the -fv options by default.
This causes output to go to /var/log/syslog, but I noticed the logs there were delayed due to buffering of the standard out i/o stream.  This caused a bunch of logs to appear in /var/log/syslog at random times with wrong timestamps.  
Example:
```
Dec 28 15:20:39 oldmacbook mbpfan[18215]: Old Temp 43: New Temp: 43, Fan Speed: 2000
Dec 28 15:20:39 oldmacbook mbpfan[18215]: Sleeping for 7 seconds
Dec 28 15:20:39 oldmacbook mbpfan[18215]: Old Temp 43: New Temp: 43, Fan Speed: 2000
Dec 28 15:20:39 oldmacbook mbpfan[18215]: Sleeping for 7 seconds
Dec 28 15:20:39 oldmacbook mbpfan[18215]: Old Temp 43: New Temp: 43, Fan Speed: 2000
Dec 28 15:20:39 oldmacbook mbpfan[18215]: Sleeping for 7 seconds …
```

Flush standard out before sleeping in verbose mode.

---

AUTHORS
Makefile
README.md
src/daemon.c
src/main.c
src/mbpfan.c
src/minunit.c

Hey Daniel,
Sorry for another/different pull request, I closed the last one. I was using multiple .git environments on my different test machines and it was creating noisy commits with old contact info stored in different scripts. Also, I wanted to update some added new distros to README.
(from the previous pull request, the last line is different now...)
Where we left off I was able to get mbpfan to compile under clang by
adding the missing return to the function in minunit.c. Our next goal
was to clean up the Makefile so you didn't have to edit it to use a
different compiler, and also clean it up since it was using a C++
compiler when all the code is C.
I think I figured out why it was using a C++ compiler. First the old C
standard didn't support boolean data types. The new standard …

Makefile cleanup, C improvements, new distros, clean up my .git

---

Makefile

Instead of calling make inside the install target to make sure that
mbpfan is compiled prior to installing, declare $(BIN) as a
prerequisite for the target. This also enables parallel compilation
from the install target in addition to avoiding unnecessary
re-linking.

Makefile: do not call make recursively inside the install target

---

src/daemon.c

Eliminates a Valgrind warning:
```
==19239== Warning: ignored attempt to set SIGSTOP handler in sigaction();
==19239==          the SIGSTOP signal is uncatchable
```

Do not attempt to catch uncatchable SIGSTOP

---

README.md

I added a table of contents for easy navigation, added the directions you provided me on figuring out if my system has applesmc/coretemp installed, I added my Macbook to tested devices, and I added Solus to supported operating systems.

TOC, coretemp/applesmc directions, Macbook support, Solus

---

src/mbpfan.c

This fixes some bugs when using the incorrect `strlen` in `strncat`.

Clean up string creation via smprintf and strdup

---

Makefile
README.md
mbpfan.service

I should thank you for this little big life saver of code. I thought maybe some simple changes, will make it better and not worse, so...
1. Why not stick to the good old way of defining objects files? So added a simple `OBJ=o`.
2. Why would we want to spam our log files every 7 seconds in `systemd`?  Other startup files are much more polite, so I removed the `-v` flag from the `systemd` one.
3. Why not be polite and give the due credits to people whom we shamefully(!) use their code? Especially if somebody wants to condemn the criminal who wrote such a horrible code!
AND YES, The last one, was a joke.

Really needed little changes.

---

README.md

There were 3 sections giving advice on how to set up systemd. Removed
2 of them.
The first one under the Ubuntu header was incomplete, it didn't start
the service immediately. The 3rd one was already mentioned in the 2nd
section.

Removed redundant systemd instructions

---

src/daemon.c

This allows the kernel scheduler to coalesce wakeups, improving
battery life.  Linux defaults to 50 ms slack.  Reference:
http://lwn.net/Articles/369549/

Configure timer slack for 1 second

---

src/mbpfan.c

This avoids unnecessary `rt_sigprocmask` and `rt_sigaction` system calls.

Call nanosleep instead of sleep in polling loop

---

README.md
src/mbpfan.c

Previously the `fopen` write mode caused the call to spuriously report
newer sensors.  Now we check the newer sensors path explicitly.  Also 
plug file descriptor leak and more carefully check return values.

Correctly test directory on Linux prior to 3.15

---

src/main.c
src/mbpfan.c
src/mbpfan.h

Default to previous values if detection fails.  Configuration can
still override these values.  Fixes #114.

Detect minimum and maximum fan speeds

---

mbpfan.conf
mbpfan.spec

To build it:
rpmbuild -ba rpmbuild/SPECS/mbpfan.spec --define 'SOURCE_VERSION 2.0.2'
It will auto configure the config file using the procedure described here:
https://ineed.coffee/3838/a-beginners-tutorial-for-mbpfan-under-ubuntu/
Maybe you could join this with this pull request:
https://github.com/dgraziotin/mbpfan/pull/154
Il will happily collaborate with Alex Dalshov (myrgy) to merge our commits in one and better organized.

RedHat/CentOS spec file to generate RPMS

---

src/mbpfan.c

MacBook Airs allow 1200-6500 and Mac Pro allow 600-5200.  Allow mbpfan
to configure smaller and larger values.

Change minimum and maximum fan speeds

---

README.md

mbpfan is _finally_ on official Fedora repository :tada:!

Official Fedora Package #181

---

mbpfan.conf

Amend the comments in mbpfan.conf around `low_temp`, `high_temp`, and `max_temp` to convey more information about what these settings actually are. The meaning was derived from the comments in this region: https://github.com/linux-on-mac/mbpfan/blob/52d897374d25fc7fc1d34425b93958aa583a0c64/src/mbpfan.c#L57-L59
Fixes: #203

Improve comments in the config around {low,high,max}_temp settings

---

Makefile
mbpfan.depend.conf

`mbpfan` service occasionally fails to start because it runs before `coretemp` is loaded, which output the following message
```/usr/sbin/mbpfan needs coretemp support. Please either load it or build it into the kernel. Exiting.```
The `systemd-modules-load.service` runs before `sysinit.target`, and `mbpfan.service` runs after `sysinit.target`. So putting a file in `/lib/modules-load.d` will make coretemp start before mbpfan.

Add coretemp as module dependency at startup

---

mbpfan.service

The run directory has been moved from /var/run to /run in systemd,
which results in the following warning at boot:
```
/usr/lib/systemd/system/mbpfan.service:10: PIDFile= references a path below legacy directory /var/run/, updating /var/run/mbpfan.pid → /run/mbpfan.pid; please update the unit file accordingly.
```
Additionally, the service occasionally fails to start if the service
is started before coretemp devices have finished probing, which results
in the following error. This patch fixes this issue.
```
systemd[1]: Started A fan manager daemon for MacBook Pro.
mbpfan[350]: /usr/sbin/mbpfan needs coretemp support. Please either load it or build it into the kernel. Exiting.
systemd[1]: mbpfan.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: mbpfan.service: Failed …
```

Fix PIDFile= reference, restart latency in systemd service

---

Makefile

If `$(DESTDIR)/lib/modules-load.d` does not exist yet, then `mbpfan.depend.conf` gets installed with that file name, instead of to `$(DESTDIR)/lib/modules-load.d/mbpfan.depend.conf`. This patch fixes the problem by ensuring the folder exists first.
Patch from AUR [1], I am the packager there. Followup to [2]. See also [3].
[1] https://aur.archlinux.org/cgit/aur.git/commit/?h=mbpfan-git&id=03288aa0926e980fbd456665047a4bda5fc9c5fd
[2] https://github.com/linux-on-mac/mbpfan/pull/253
[3] https://github.com/linux-on-mac/mbpfan/issues/255

Ensure lib/modules-load.d exists before installing there

---

src/mbpfan.c

In newer versions of Linux and/or Apple devices, the applesmc module uses a different "/sys/devices" path to map the fan controller to.  This seems to be due to changes in how ACPI devices are mapped to the "/sys/devices" directory. 
*changes*
If the original hardcoded "applesmc" device path is not found, dynamically look for the device path to the "applesmc" device root by searching sub-directories of "/sys/bus/acpi/drivers/applesmc". Once the device path has been found, setup the fan device path root.
*testing*
Tested on Macbook Pro 2019 (16,1), Fedora 33, Kernel: 5.13.12-200.mbp15.fc33.x86_64

Add support for alternate applesmc module device path.

---

src/util.c

When building with clang-16, the following build error is raised.
clang -c -O2 -march=x86-64 -pipe -pipe -frecord-gcc-switches -fno-diagnostics-color -fmessage-length=0  -g  -Wall -Wextra -Wno-unused-function -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=500 src/util.c -osrc/util.o src/util.c:13:9: error: call to undeclared function 'vsyslog'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
vsyslog(level, fmt, args);
^
src/util.c:13:9: note: did you mean 'syslog'?
/usr/include/syslog.h:62:6: note: 'syslog' declared here void syslog (int, const char *, ...);
This is due to vsyslog being available when _GNU_SOURCE or _BSD_SOURCE is defined [1]. This patch does that, thus fixing the error.
[1]: https://linux.die.net/man/3/vsyslog
Bug: …

src/util.c: Fix build with clang-16

---

.clang-tidy
Makefile
src/daemon.c
src/daemon.h
src/mbpfan.c

Do not call signal-unsafe functions in handler
